### ISSUE TITLE
Problema cache?

### ISSUE THREAD

**Issue by nitaku** [nitaku/webvis_lab#1]
A volte le modifiche al codice (almeno per i coffee) non vengono effettuate quando si fa run.
Come riprodurre: aggiungere console.log 'qualcosa' ad un coffee, aprire la console e fare run.

**Comment by andreaderrico2** [comment]
Con l'aiuto di Fabio dovrebbe essere sistemato questo bug... Era ovviamente un problema di chiamate asincrone che dovevano essere sincrone...
Ho adottato questo sistema qui: http://stackoverflow.com/questions/5821380/how-to-make-a-jquery-post-request-synchronous

Però sembra che per i browser sia deprecato, per questo, anche se mi sembra stia funzionando, non chiudo l'issue. Prima ne volevo discutere con voi...

Questo è quello che dice la console a riguardo: "Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/"

**Comment by andreaderrico2** [comment]
Come non detto... La chiamata Ajax sincrona sembra darmi problemi con altre istruzioni (che sembra non vedere proprio) presenti nella stessa funzione...

**Comment by andreaderrico2** [comment]
Dopo l'intervento di Matteo è stato risolto il problema derivante da funzioni asincrone
